# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: DogDog # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs10.15
  region: na-toronto # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 64 # 内存大小，单位MB
  timeout: 900 # 超时时间，单位秒
  events: #触发器
    - timer: #超级直播间红包雨
        parameters:
          name: Live-RedRain
          cronExpression: "0,2 0,30,31 20-23/1 20 4 * *"
          enable: true
          argument: jd_live_redrain
    - timer: #整点京豆雨
        parameters:
          name: Super-RedRain
          cronExpression: "3 0 * * * * *"
          enable: true
          argument: jd_super_redrain&10_redrain
    - timer: #东东超市兑换奖品
        parameters:
          name: Redeem-Supermarket
          cronExpression: "52/1 59 23 * * * *"
          enable: true
          argument: jd_blueCoin
    - timer: #争分夺秒新一天-1
        parameters:
          name: New-Day-1
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_bean_sign
    - timer: #争分夺秒新一天-2
        parameters:
          name: New-Day-2
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_shop&jd_sgmh
    - timer: #店铺签到
        parameters:
          name: Shop-Sign
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: monk_inter_shop_sign
    - timer: #杂七杂八-1
        parameters:
          name: Miscellaneous-1
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: z_xmf&jd_club_lottery&jd_rankingList
    - timer: #杂七杂八-2
        parameters:
          name: Miscellaneous-2
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_lotteryMachine&z_marketLottery
    - timer: #锦鲤红包
        parameters:
          name: Red-Packet
          cronExpression: "30 1 1,2,23 * * * *"
          enable: true
          argument: jd_redPacket_new&jd_speed_redpocke
    - timer: #十元街/赚京豆小程序
        parameters:
          name: SYJ
          cronExpression: "0 5 1,23 * * * *"
          enable: true
          argument: jd_syj_new
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
