
name: 简单天气

on:
  workflow_dispatch:
  schedule:
     - cron: '5,35 0-14,21-23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【简单天气】'
        run: |
          node Task/jdtq.js
