name: 腾讯自选股养牛

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      
      USERHEADER: ${{ secrets.TXS_USERHEADER }}
      USERKEY: ${{ secrets.TXS_USERKEY }}
      SIGNHEADER: ${{ secrets.TXS_SIGNHEADER }}
      SIGNKEY: ${{ secrets.TXS_SIGNKEY }}
      TASKHEADER: ${{ secrets.TXS_TASKHEADER }}
      TASKKEY: ${{ secrets.TXS_TASKKEY }}
      WXTASKKEY: ${{ secrets.TXS_WXTASKKEY }}
      COWKEY: ${{ secrets.TXS_COWKEY }}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}
      BARK_SOUND: ${{ secrets.BARK_SOUND }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        
        run: |
          npm install
      - name: '运行 【腾讯自选股养牛】'
        
        run: |
          node Task/TXStockCow.js
